### ISSUE TITLE
Property changed callback not firing

### ISSUE THREAD

**Issue by Myrmex** [nippur72/PolymerTS#1]
Hi, I'm playing with Polymer + TS and I've found these definitions. I'm experiencing an issue when trying to react to a change in a 2-way bound property: the *changed callback never gets called*. Yet, as far as I can see by debugging it is correctly defined in the object prototype, and I get no errors in the console. I found no code example for observing a property change in your source, so maybe it's just me doing something stupid.
My element is fairly simple as this is just a test: its template contains an input to be 2-way bound to a property named `text`:

    <input autofocus value="{{text}}" placeholder="enter text"/>

The TS relevant code is (note the `notify:true` and the callback named after the documented convention):

    @tag("my-element")
    class MyElement implements PolymerElement {
      @property({type: String, value: "example", notify: true })
      public text: string;
      ...
      public textChanged(): void {
          // this.text should contain the new value. Anyway this never gets called.
      }
  }

Could anyone suggest a solution?

**Comment by nippur72** [comment]
I'm investigating it right now. What's strange is that I'm not able to make it work even with the normal polymer registration (without PolymerTS)!

Anyway you are missing `::input` in your markup:
```HTML
<input value="{{text::input}}"/>
```

**Comment by nippur72** [comment]
Ok, found it!

With the new 1.0 API, `notify: true` will trigger an event `text-changed` not a call to to `textChanged()`.

So you have two options:

1) turn your function into an event listener:
```typescript
@listener("text-changed")
public textChanged(): void {
   // this.text should contain the new value. Anyway this never gets called.
}
```

2) add an observer for `text`:
```typescript
@property({type: String, value: "example", observer: 'textChanged' })  // no notify: true
public testo: string;
```
