### ISSUE TITLE
TypeScript 2.4 weak types often break decorators

### ISSUE THREAD

**Issue by 43081j** [nippur72/PolymerTS#101]
As per:
https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/

An interface (in our case `polymer.Element`) which has all optional types is not considered implemented unless at least one of the types exists (one of the properties). This causes a huge amount of compile errors when using the decorators (`no properties in common with type 'Element'`).

There's a few ways we could fix this, I guess:

* Add a required type (maybe `prototype` shouldn't be optional?)
* Set the target as `polymer.Base` instead
* Add an index signature
* Default `properties` to an empty array (or listeners or something so we can have a required property)

Here are the suggestions Microsoft make:

> * Declare the properties if they really do exist.
> * Add an index signature to the weak type (i.e. [propName: string]: {}).
> * Use a type assertion (i.e. opts as Options).

Simplest solution appears to be to use `polymer.Base` in decorators rather than `polymer.Element`. does this still make sense/seem right?

**Comment by iainreid820** [comment]
I've created a PR that resolves this be declaring the Element interface as an extension of the PolymerBase interface #103.

**Comment by kito99** [comment]
I'll try to review/test this this week.

**Comment by kito99** [comment]
Ended up taking a different route to avoid any backwards compatibility issues. Most of the problems were with deprecated methods like `createElement()` and `createClass()`.
