### ISSUE TITLE
Relying on global scope means PolymerTS cannot be used in JS bundles

### ISSUE THREAD

**Issue by 43081j** [nippur72/PolymerTS#107]
If we bundle polymerTS with something like webpack, it will be wrapped in a function like so:

```javascript
function() {
  var polymer;
  // ...
  function observe(...) {
    // ...
  }
}
```

This means `polymer` is local to the function, rather than becoming `window.polymer`.

So [this assignment](https://github.com/nippur72/PolymerTS/blob/0.2.2/polymer-ts.js#L13) will fail because `window["polymer"]` is non-existent.

---

Similarly, this means observers also don't work in such situations because the functions are local to the function scope. Meaning things like `observe` are never exposed.

The only suggestion I have right now is to simply declare everything on `window` (such as `window.observe = ...`). As we don't really have the option to turn it into an export.

Or we assign `polymer` to window, and aliases of the decorators to `polymer`?

**Comment by kito99** [comment]
@43081j you use Webpack with PolymerTS, right? How do you handle this?

**Comment by 43081j** [comment]
I have a second entry point in my webpack `entry` array before my usual entrypoint, which is a file that essentially does this:

```
window.polymer = window.polymer || {};
```

This sorts out the first problem.

However, the second problem seems impossible to work around. The decorators simply aren't exposed, so you can't possibly get a reference to them. Fortunately, I only use two of the decorators, so I am maintaining my own decorator functions for now to get around this.

**Comment by seqai** [comment]
I have the same problem, another workaround, the one I use is quite ugly, yet it works. You can use script-loader, which just loads the script as it was referenced directly as script:
```            
{
    test: /polymer-ts\.min\.js$/,
    use: "script-loader"
}
```
with these references in my vendor entry point:
```
/// <reference path="../bower_components/polymer-ts/polymer-ts.d.ts" />
import "../bower_components/polymer-ts/polymer-ts.min.js"
```

**Comment by kito99** [comment]
I think this is worth deferring to a solution based on Polymer 2.0 (or 3.0) and [PolymerDecorators](https://github.com/Polymer/polymer-decorators).
