### ISSUE TITLE
Add support for complex observers even when using simple properties

### ISSUE THREAD

**Issue by kito99** [nippur72/PolymerTS#111]
> NOTE: The 'current' behavior described here is for PolymerTS .21 and earlier. .22 has the bug described in #104.

Right now, if you want to create an observer for a single property, you can do this:

```typescript
@observe('foo')
private _fooChanged(newFoo: string, oldFoo: string) {
}
```

This is the same as doing this with pure JavaScript:

```javascript
...
    properties: {
      foo: {
        type: String,
        observer: '_fooChanged'
      }
    }
...
 _fooChanged(newFoo: string, oldFoo: string) {
}
```

Polymer only supports one simple observer per property. 

You could also create a "complex" observer; usually this is used for multiple properties, but it can also be used for a single property. This allows you to support multiple complex observers for a single property. Here's an example in JavaScript:

```javascript
...
  observers: [
    '_fooChanged(foo)',
    '_fooAlsoChanged(foo)'
  ]
...
```

Currently PolymerTS doesn't support this case, because `@observe('foo')` should create a simple observer, not a complex observer. The proposal is to add a single boolean property that tells PolymerTS to create a complex observer instead:

```typescript
@observe('foo', true);
private _fooChanged(foo: string) {
...
}

@observe('foo', true);
private _fooAlsoChanged(foo: string) {
}
```

> NOTE: PolymerDecorators supports an array in order to indicate a complex observer, which is probably a better approach: https://github.com/Polymer/polymer-decorators

**Comment by 43081j** [comment]
Unfortunately your `0.2.3` introduced a breaking change and failed every build we have in CI.

You should have actually bumped to `0.3` in this case to prevent such a scenario (bower auto-updating to bugfix versions).

Any chance you could try take a look at this very soon? We will have to tie our builds into the previous version for now. 

---

As for this actual issue. Multiple `@observe` calls to the same property should most definitely be appended to the observers array. This is how the official decorators will work too.

The edge case should be the `(new, old)` observer, meaning if any special syntax is introduced, it should be for that. Not for repeated observers.

**Comment by kito99** [comment]
@43081j thanks for pointing this out. I can look at this in the next week or so. We need to come up with a logical approach for handling both cases. I'm not fond of changing the current behavior, since that's likely to break far more builds and require more changes for existing projects. I also don't consider a simple observer to be an edge case; it's certainly not in several of my clients' apps.

I'll take a closer look at how the Polymer Decorators project handles this.

**Comment by kito99** [comment]
So I took a look at the Polymer Decorators code, and from what I can tell, it doesn't support simple observers at all (@43081j please correct me if I'm wrong).

**Comment by 43081j** [comment]
Simple observers don't have their own decorator because we can just do it by reference:

```ts
@property({ observer: MyElement.prototype.onChange })
```

Unless you really need the old value, the decorator is enough. In the rarer cases where you care about the old one, you can do the above.

**Comment by kito99** [comment]
@43081j Now that's been a couple months and I still haven't had time to do this, is it still important to you? I haven't heard any other requests, and this point I'm more interested in moving all of our projects to Polymer 2 and Polymer Decorators.

**Comment by 43081j** [comment]
@kito99  don't worry about it. if current behaviour works for those who use polymerTS right now, leave it as is.

i migrated most of my projects to polymer-decorators so this doesn't affect me anymore. at this point its probably best to just maintain the interfaces/behaviour that are already in here.
