### ISSUE TITLE
PolymerTS starter kit using gulp nodejs and visual code

### ISSUE THREAD

**Issue by gertcuykens** [nippur72/PolymerTS#28]
Trying to get PolymerTS working in this fork

https://github.com/gertcuykens/polymer-starter-kit

**Comment by gertcuykens** [comment]
@nippur72 I am already stuck, can you look at the code and tell me how I would make visual code compile this part? https://github.com/gertcuykens/polymer-starter-kit/blob/master/app/elements/my-greeting/my-greeting.ts

**Comment by nippur72** [comment]
I emailed you a sample app of the above element that can be edited with visual code and compiled with "tsc" from command line. 

I suggest you to setup a repo, so if needed we can fork it and edit

**Comment by gertcuykens** [comment]
Thanks, Yep I did https://github.com/gertcuykens/polymer-starter-kit

**Comment by gertcuykens** [comment]
@nippur72 Visual code syntax is working now thanks.

For now I will drop this file because it is going to mess up the original one.

https://github.com/gertcuykens/polymer-starter-kit/blob/master/app/scripts/app.ts

Also its very important a mix of ts en non ts is working together and currently it does.

https://github.com/gertcuykens/polymer-starter-kit/blob/master/app/elements/my-greeting/my-greeting.ts

https://github.com/gertcuykens/polymer-starter-kit/blob/master/tsconfig.json

And now the difficult part how and where to cram tsc build somewhere in the gulp.js?

https://github.com/gertcuykens/polymer-starter-kit/blob/master/gulpfile.js

As a side note I think bower install nippur72/PolymerTS needs to be modified like removing Sample and and make it look more like the other bower_components ?

The very last step is a gulp task that generates a tsconfig.json if everything els is working.

**Comment by gertcuykens** [comment]
@nippur72 forget the above for a minute, I am been tinkering around and I now do two commands in the project directory.

tsc
gulp serve

Which is good enough. There are two issues that need to be fixed now.

1) tsc error's on the Sample directory
2) Atter removing Sample directorie in bower_components it compiles but gulp serve result in a side with Uncaught ReferenceError: polymer is not defined on the generated js file from tsc 

```js
        property({ notify: true })
    ], MyGreeting.prototype, "greeting");
    MyGreeting = __decorate([
        component("my-greeting")
    ], MyGreeting);
    return MyGreeting;
})(polymer.Base); <=========
MyGreeting.register();
```

**Comment by gertcuykens** [comment]
@nippur72 And whats up with `error TS5023: Unknown compiler option 'experimentalDecorators'.` if i add it tsc start complaining if I don't tsc works but V code starts complaining...

Also the error above is because of `polymer.Base` needed to be `Polymer.Base` but I know have a bunch of other errors.

**Comment by gertcuykens** [comment]
The second issues was because I forgot to do `<link rel="import" href="../bower_components/polymer-ts/polymer-ts.html">`

**Comment by gertcuykens** [comment]
I think tsc compiling source maps is useless in this case?

**Comment by nippur72** [comment]
IMO it's better to have a `tsconfig.json` and tell explicitly what files to compile. `tsc` only will try to compile everything it finds :-)

As for the `--experimentalDecorators` flag, make sure you have the latest TypeScript (1.5.3 as of today). The flag tells it's ok to use decorators, which is yet considered an experimental feature.

**Comment by gertcuykens** [comment]
Hmm for a starter kit it needs to do that :) 
I think this would be good enough now 

https://github.com/gertcuykens/polymer-starter-kit
tsc -w & gulp serve 

Disabling tsc generated maps because of second gulp build that screws up the mapping anyway. Can you exclude the Samples from bower.json and add a minified version? Then I can ask the polymer team if they have other suggestion to add.

**Comment by nippur72** [comment]
oops `Sample` was not meant to be shipped :-) I'll updated `bower.json`.

**Comment by gertcuykens** [comment]
Ok thanks :) ps should I worry about this file when using tsc compiling everything it finds?
https://github.com/nippur72/PolymerTS/blob/master/polymer-ts.ts

**Comment by gertcuykens** [comment]
crap the distribution step `gulp` doesn't seem to handle the generated js file correctly and doesn't get vulcanised correctly :(

**Comment by gertcuykens** [comment]
found a way around it, but can you look at the gulp jshint output warnings from the compiled file ?

```js
  line 2   col 22  Expected '{' and instead saw 'if'.
  line 2   col 47  Expected '{' and instead saw 'd'.
  line 8   col 36  Strings must use singlequote.
  line 8   col 78  Strings must use singlequote.
  line 8   col 80  Expected '{' and instead saw 'return'.
  line 17  col 24  'MyGreeting' is already defined.
  line 19  col 35  Strings must use singlequote.
  line 23  col 40  Strings must use singlequote.
  line 24  col 5   'MyGreeting' is a function.
  line 25  col 32  Strings must use singlequote.
  line 22  col 9   'property' is not defined.
  line 25  col 9   'component' is not defined.
  line 28  col 4   'polymer' is not defined.```

**Comment by gertcuykens** [comment]
I think .jshintrc need to be modified?
```json
{
  "node": true,
  "browser": true,
  "esnext": true,
  "bitwise": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "immed": true,
  "indent": 2,
  "latedef": true,
  "noarg": true,
  "quotmark": "single",
  "undef": true,
  "unused": true,
  "globals": {
    "wrap": true,
    "unwrap": true,
    "Polymer": true,
    "Platform": true,
    "page": true,
    "app": true
  }
}
```

**Comment by gertcuykens** [comment]
I modified gulpfile.js

`gulp serve` works
but default `gulp` doesn't

**Comment by gertcuykens** [comment]
PS do pull request first :) I made some changes

**Comment by gertcuykens** [comment]
Safari doesn't like it?

```js
[Error] ReferenceError: Can't find variable: Polymer
	n (app.js, line 1)
	register (app.js, line 1)
	global code (app.js, line 1)
```

**Comment by nippur72** [comment]
I don't have a Mac to test on Safari, but perhaps it's the same issue with `webcomponents.js` we have  in IE and FF. From the README.md:

*Note: due to an issue in WebComponents, you can't use the `<script>` tag on the main page to load PolymerTS or custom elements, you have always to use the `<link rel="import">` syntax.*

*This will make sure that scripts will be loaded in the correct order in all browsers.*

*If for some reason you want to use script inclusion for your elements, you have to load Polymer and PolymerTS via script too. Polymer doesn't have a polymer.js file (it's shipped as .html only), but you can get one from greenify/polymer-js.*

so turn these:
```
<script src="scripts/polymer-ts.js"></script>
<script src="scripts/my-greeting.js"></script>
```
into `<link rel="import">`

**Comment by gertcuykens** [comment]
Ok, I did so for polymer-ts, but for my-greeting.js I can't because i don't know any other way to generate and include it with gulp? 

(See new commit)

**Comment by nippur72** [comment]
Sorry, as regards `my-greeting.js`, I meant to tell you to include it from element's `.html` file.

BTW, I think (but I might be wrong) a good pattern is to have `.ts` files in the same `elements` directory along with the `.html` files. 

Having them in the same directory helps switching back and forth from template to code. 

So loading the `.js` is just a matter of:
```HTML
<!-- this is my-greeting.html -->
<dom-module> ... </dom-module>
<script src="my-greetings.js"></script>
```

**Comment by gertcuykens** [comment]
ok going to try that, ps did you had time to also look at jshint trowing allot of warnings on the generated code?

**Comment by gertcuykens** [comment]
js files are now in the same elements directory but still have to reference it in index els the vulcanizing step is not happy

(see new commit)

**Comment by gertcuykens** [comment]
Never mind it works now, probably a typo. Anyway jshint is still bothering me see new commit

**Comment by gertcuykens** [comment]
Never mind I just disabled it for js files in elements directory, so the final version would be something like this, let me know if you have any other recommendations? getting it in the main repo from Polymer is not going to happen grrrr So may creating a yo generater aldo I dont like yo, I like git clone :)

**Comment by cbfranca** [comment]
@gertcuykens have some sample using PolymerTs + polymer-cli / polymer-build ?

**Comment by gertcuykens** [comment]
The way to go now is ES6 in full throttle, try to make your stuff work without using polymer its less painful then you expect.
https://github.com/gertcuykens/hello-world
https://github.com/gertcuykens/decorators
