### ISSUE TITLE
Annotated Event Listeners

### ISSUE THREAD

**Issue by bhsnll** [nippur72/PolymerTS#33]
The polymer website describes how to setup annotated event listeners:

https://www.polymer-project.org/1.0/docs/devguide/events.html

Simply writing another function on my custom element's class however does not expose the function properly. For example:

My .ts
```javascript
@component('my-element')
class MyElement extends polymer.Base {
  public myFunction():void {
    console.log('Hello!');
  }
}
MyElement.register();
```

My .html
```html
<dom-module id='my-element'>
    <template>
        <button on-click='myFunction'>Click Me!</button>
    </template>
</dom-module>

<script src='/my-element.js'></script>
```

In the console it logs: `[my-element::_createEventHandler]: listener method 'myFunction' not defined`. Is there a way to do this in Polymer TS?

**Comment by nippur72** [comment]
I've tried your example on IE,FF,Chrome and it works normally. Perhaps it's something related to setup of project?

If you still have this issue, setup a repo (or other way) so I can tell you what's wrong.

**Comment by bhsnll** [comment]
I just finished rechecking this. The problem was in how my project was setup. Somehow I didn't reference polymer-ts.js correctly but the only thing that broke was the annotated event listeners. Which is kind of weird really because everything else seemed to be working just fine. Not sure why that was... I'm doing some interesting things with gulp in how my components are built out so maybe that has something to do with it. But thanks for the quick reply! PolymerTS is great!
