### ISSUE TITLE
@observe does not work on path changes

### ISSUE THREAD

**Issue by dandelionmane** [nippur72/PolymerTS#36]
Per the polymer guide, to observe path changes, one needs to add an observer to the list of observers, rather than adding it as a property annotation: ([observing path changes](https://www.polymer-project.org/1.0/docs/devguide/properties.html#observing-path-changes))

However, currently the decorator will add an observer to the list of observers only if it has a comma, and will not add it to the list of observers if it has a dot. This can be fixed pretty simply by checking for a period as well as a comma when deciding which invocation to use. (I would submit a change myself, but I believe I am blocked by the lack of a LICENSE on the repository).

I would appreciate if this could be fixed in a release soon.

**Comment by nippur72** [comment]
Ok, I fixed it, but there's a problem I was not able to figure out. 

Polymer calls the observer function 3 times during the initialization phase, I really don't know why. I suspect it's a Polymer issue, so could you please verify that, in case we might open an issue on the Polymer repo. 

Look at `tests.ts`:
```TypeScript
         expect((<ObserverTest>el).nmanager_changed).toBe(0); // but it's 3!        
         el.set("user.manager", "42");                           
         expect((<ObserverTest>el).nmanager_changed).toBe(1); // but it's 4!        
```

**Comment by kito99** [comment]
This appears to have been fixed and merged. Closing.
