### ISSUE TITLE
Two way binding with <input value="{{myProperty}}" />

### ISSUE THREAD

**Issue by m0b0u0** [nippur72/PolymerTS#41]
I'm trying out PolymerTS, with some basic experience in plain Polymer 1.0. Not sure I want the decorators but I could not get it to work without them. I am using TypeScript 1.5.

Now, I was able to bind a property to display to a **div** and to bind one-way to an **input** (to display the initial input value), but I've not been able to bind two-ways to the **input** : ts/js code is not getting the new value of the bound property if the user types something in the input, the value of the property remains the initial value no matter what I type in the input field.

*Example:* 
```
(.html)
<input type="text" value="{{userName}}" />
(.ts:)
@property({ readonly: false }) userName = "myself";
```

p.s.: I tried with Polymer's **paper-input** as well, but no luck: 
    ```<paper-input value="{{userName}}"></paper-input>```

Again, note that binding to a div works fine, as in this example:
```
(.html)
<template is="dom-repeat" items="{{tables}}">
  <div>{{item}}</div>
</template>
(.ts)
@property({ type: Array, value: function () { return []; } }) tables;
...
this.set('tables', myTableArrayData);
```

Thank you !

**Comment by nippur72** [comment]
see #1 likely you need:
```HTML
<input value="{{text::input}}"/>
```

**Comment by m0b0u0** [comment]
Thank you, I was missing the "::input" indeed!
*p.s. well actually it did work without the "::input" on a paper-input tag*, my mistake.

Closed.
