### ISSUE TITLE
@template doesn't work with arrays

### ISSUE THREAD

**Issue by aabluedragon** [nippur72/PolymerTS#42]
`@template` fails to work with arrays (using dom-repeat), console output is:
```Polymer::Attributes: couldn`t decode Array as JSON```

**Comment by nippur72** [comment]
Looks like a `webcomponentjs` issue. 

I made a new release of PolymerTS, forcing it to ask for `webcomponentsjs` >=0.7.10, where some issues are fixed. It should work at least on Chrome and FF (IE is bugged, but I'm investigating it).

Can you please confirm this new rel works on Chrome and FF for your issue?

Just run a `bower update`.

**Comment by aabluedragon** [comment]
Fix confirmed.
Thanks!

**Comment by nippur72** [comment]
I fixed also the case for IE11, just update to latest (0.1.13)

**Comment by Kilometers42** [comment]
Can this solution be extended to deal with dom-repeat not working inside table tags in IE11? (see https://github.com/Polymer/polymer/issues/1735)

**Comment by nippur72** [comment]
no, this fix works only for the `@template` decorator, but perhaps it might get fixed with the next webcomponents as they solved the issue with `<template>` and `innerHTML`.

See [Polymer/polymer/issues/2114](https://github.com/Polymer/polymer/issues/2114)

**Comment by nippur72** [comment]
and, btw, try using `webcomponents.js` instead of `webcomponents-lite.js`, see if it works.
