### ISSUE TITLE
Inconsistent change handler param order

### ISSUE THREAD

**Issue by almstrand** [nippur72/PolymerTS#47]
Change handlers in Polymer take two parameters; the first one representing the old property value and the second representing the new value.

However, in polymer-ts, the order is reversed, e.g.:

```
// single property observer
@observe("name");
nameChanged(newName,oldName)
{
   // ... 
}
```

This may be a bit opinionated, and of course polymer-ts can change the order, but to remain as API-compatible as possible and not to confuse users coming from the non-typescript world, it may be preferred to match the parameter order as defined in Polymer:

```
// single property observer
@observe("name");
nameChanged(oldName,newName)  // "oldName, newName" instead of "newName, oldName"
{
   // ... 
}
```

**Comment by nippur72** [comment]
this is another thing that changed from 0.5 to 1.0 :smiley:  

From the [migration guide](https://www.polymer-project.org/1.0/docs/migration.html#properties):
```
fooChanged: function(newValue, oldValue) { 
    ... 
  }
});
Note that the arguments to the observer are 
currently in the opposite order compared to 0.5.
```

**Comment by almstrand** [comment]
I see--yes polymer-ts conforms with the Polymer 1.0 API then :) Sorry for the false alarm.
