### ISSUE TITLE
The generated polymer-ts.d.ts requires noImplicitAny

### ISSUE THREAD

**Issue by jjrv** [nippur72/PolymerTS#48]
Due to [missing types on lines 111-113](https://github.com/nippur72/PolymerTS/blob/6596cedfb7ac36410f772b723ccac690a45bbcdc/polymer-ts.d.ts#L111-L113) in the generated `polymer-ts.d.ts`, code using this library must have `noImplicitAny` set to `true` to compile.

It seems changing `polymer-ts.ts` [lines 327-329](https://github.com/nippur72/PolymerTS/blob/6596cedfb7ac36410f772b723ccac690a45bbcdc/polymer-ts.ts#L327-L329) would fix this.

**Comment by nippur72** [comment]
thank you for the PR, merged and released.
