### ISSUE TITLE
Write .d.ts definition files

### ISSUE THREAD

**Issue by nippur72** [nippur72/PolymerTS#5]
The library needs to be written as a `.d.ts` file so that can it be published on DefinitelyTyped and imported more easily.

**Comment by lgrignon** [comment]
NB: I did generate the .d.ts file in my PR ;)

I wrote the first polymer.d.ts file for 0.5 but it seems that someone recently upgraded the defs to 1.0. I think it is conflicting in some way. Maybe we should leave a comment on Def Typed discussion.

**Comment by nippur72** [comment]
Since this package requires both code and definitions, I wonder if it's better to avoid the `.d.ts` published on DefinitelyTyped and simply ship the `polymer-ts.ts` (to import and to reference in the ts code).

**Comment by herkulano** [comment]
IMO publishing it on DefinitelyTyped would help more people to use it, simply because it has more visibility.

**Comment by lgrignon** [comment]
Hello.
I think it is better to push the .d.ts on Definitely Typed, and to reference the existing [polymer.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/polymer/polymer.d.ts) in our polymer-ts.ts

Because :
* Developers will probably get polymer-ts.js via bower and will use something like bower concat or equivalent, and won't event know there is a .ts file behind the scene
* However, they will want to extend the classes in their TS code, thus will need to use the polymer-ts.d.ts

This is good spec / impl isolation.

The thing I hate is that the current author of polymer.d.ts chose to name the root interface polymer.Base and not polymer.Element ! The sad thing, beyond this ambiguous naming is that our actual base class is also polymer.Base therefore, the merge could be much more painful than it seems.

Please tell me your thoughts about it.

**Comment by nippur72** [comment]
Ok regarding the spec / impl isolation, it makes sense.

The only problem is that our package clashes with the existing polymer.d.ts, perhaps we should have two different .d.ts packages:

* `polymer.d.ts` (what's published now) to let users work with the plain version of Polymer, old javascript style
* `polymer-ts.d.ts`to let user work with our package

The second option is a forced choice if we have to ship our version of `polymer.js` please see #30

**Comment by lgrignon** [comment]
Yes, as I suggested, polymer-ts.d.ts and polymer.ts should depend on polymer.d.ts as a ///<reference

For the second problem, let's wait for the polymer's team answer :)

**Comment by herkulano** [comment]
@nippur72 

Regarding `polymer.js`, @greenify created an automated process to extract the javascript insinde `polymer.html` : https://github.com/greenify/polymer-js

It's a long discussion, but we've been looking into using polymer with jspm and came across the same issue : https://github.com/biojs/biojs3/issues/4

We've also posted in polymer issues and got an negative answer from the Polymer team : https://github.com/Polymer/polymer/issues/1133

In sum, there are no plans to support `polymer.js` in the near future and @greenify's solution works well.

**Comment by nippur72** [comment]
@herkulano thanks, well at least we have an alternative. Currently I switched back to suggesting the use of HTML Imports, but at least now it's not a must, it's an option :-)

**Comment by nippur72** [comment]
I've added the generated `.d.ts` file to the bower package, so that user installing PolymerTS can get it and reference it the more traditional way (include .js and reference .d.ts).

Next step is adding this to DefinitelyTyped.

**Comment by nippur72** [comment]
I'm closing this issue, my actual understanding is that DefinitelyTyped is for pure JavaScript libraries (not originally written in TypeScript).

Libraries written with TypeScript can ship their `.d.ts` file and users can reference it directly from the `bower_components` directory (instead of `typings`). So there's no need to pass through DefinitelyTyped.

**Comment by lgrignon** [comment]
Hello :)

  I am sorry but I think we should still publish the definition file on DefinitelyTyped. Indeed, the fact that the library is initially coded in TypeScript or Dart or whatever is actually an implementation detail. Developers will only install it via bower and add the library's definition file from tsd as they are used to do.

  In addition, it is not necessarily a bad thing to provide both options, don't you think?

  I am ready to push the def file on def typed if you allow me to do that.

**Comment by nippur72** [comment]
Ok thanks, feel free to push the `.d.ts` on def typed. 

Make sure you have the `0.1.17` of today.

**Comment by lgrignon** [comment]
Yes, thanks :)
