### ISSUE TITLE
function expression can not be observer

### ISSUE THREAD

**Issue by Seamus6869** [nippur72/PolymerTS#52]
When using either:
`@property({... observer: "dataChanged" })`
`data: any;`

or
`@observe("data")`
`public dataChanged(newValue, oldValue)`

The observer works as expected, however if I change the function to be a function expression like this:
`public dataChanged = (newValue, oldValue) => {...`

The observer breaks and I get an error that the observer method "dataChanged" can not be found. I need the ability to use a function expression so that I can control the `this` reference inside of my event handler. If anyone can help point me in the right direction I can work on PR for this.

Thanks!

**Comment by nippur72** [comment]
I don't have this issue:
```TypeScript
   @property() baz="mybaz";
   @observe("baz")
   changedBaz = (newVal, OldVal) => {
      this.nbaz_changed++;
   }
```
In Jasmine:
```TypeScript
      it("observes a single property changes as a lambda function", () => {
         expect((<ObserverTest>el).nbaz_changed).toBe(0);         
         el.set("baz", "42");
         expect((<ObserverTest>el).nbaz_changed).toBe(1);         
      });
```
Jasmine spec-runner output:
```
@observe decorator
   observes a single property changes as a lambda function
```

**Comment by Seamus6869** [comment]
Thank you. We did some testing with your example and saw the same thing. There is a bug somewhere else in our system.

**Comment by nippur72** [comment]
looking at console's output I see there is a warning from Polymer in this regard. Is that what are you talking about? or is it a true error?

**Comment by Seamus6869** [comment]
I get a message like this in the console:
`polymer.html:1442 [elynx-grid::_observerEffect]: observer method 'dataChanged' not defined`
We thought this was causing the observer not to fire but it turns out there was a different issue.

**Comment by nippur72** [comment]
I think polymer sends out that warning because the lamba-observer-function is defined by typescript only at the time of constructor(), so it's missing at the time of registration.
