### ISSUE TITLE
Error in polymer-ts.ts

### ISSUE THREAD

**Issue by ericdes** [nippur72/PolymerTS#61]
Hello, and thank you for the nice work!

The compiler complains when processing polymer-ts.ts / polymer-td.d.ts: "A class may only extend another class." at: `export declare class PolymerBase extends HTMLElement`

**Comment by nippur72** [comment]
Are you using TS < 1.6, right?

With TS 1.6 `HTMLElement` is no longer an interface but a true class, so `Polymer.Base` extends from it (and thus making available all HTMLElement methods). 

We introduced this change since 0.1.17:
```
v0.1.17 (Sep 14, 2015)
- BREAKING CHANGE: (mostly harmless) Polymer.Base is now an extension of HTMLElement
```

Can you please confirm it's a version issue, and in case, it's a problem for you to upgrade?

**Comment by ericdes** [comment]
That was the problem indeed. I upgraded to tsc 1.6+ and it is working.

**Comment by harryjoy** [comment]
I still see this issue. (at least with d.ts file)

```
$ tsc --version
message TS6029: Version 1.7.3
```

I get this when I reference polymer-ts.d.ts buy when I reference polymer-ts.ts everything works fine. Should I be referencing .ts only and not d.ts?

**Comment by nippur72** [comment]
that's strange, as the `.d.ts` file is generated directly from `.ts`.

That error is generated when an old `lib.d.ts` is automatically linked by typescript, so make sure you have the latest both in node.js and visual studio. 

BTW there is a newer is `1.7.5`.

**Comment by harryjoy** [comment]
```
$ tsc --version
message TS6029: Version 1.7.5

$ node --version
v5.3.0

$ npm --version
3.3.12
```
Still getting same error for d.ts and not for .ts.

Its really strange I can successfully compile and run using .ts and while using .d.ts it breaks on the compile.

**Comment by harryjoy** [comment]
Ohk! Got it.

It is because gulp-typescript task is using typescript of its own and that is of older version. It is not picking the global tsc but one from its dependencies and that is causing problems. I need to see on the gulp-typescript if they have updated to be latest.

Thanks for the support.

**Comment by nippur72** [comment]
very good!
