### ISSUE TITLE
Base.prototype.register() fails with extending class hierarchies

### ISSUE THREAD

**Issue by ntelementary** [nippur72/PolymerTS#62]
When inheriting from a polymer.Base derived class, the Register() method on the class prototype fails to work as expected.
1. The derived element cannot fire Register without the error "element already registered in Polymer".
   (Fix: #57)
2. In addition to the issue in addressed in #57, the extended element fails to correctly call the derived overrides.
   (Workaround: order registration from child to parent. See below)

These problems occur **regardless of the import structure**, so a single file example is enough to demonstrate the issue:

``` typescript
// base-element.ts
import 'polymer-ts';

@component('base-element')
export class BaseElement extends polymer.Base {
    ready() { 
        console.log(this.is + " element is ready!");
    }
}

BaseElement.register();

@component('new-element')
export class NewElement extends BaseElement {
    ready() { 
        // FAILS: even with the fix from #1, this override will not fire correctly.
        super.ready();
        console.log("this element is ready!");
    }
}

// FAILS: With "element already registered in polymer"
NewElement.register();
```

<img width="749" alt="screen shot 2015-10-12 at 7 36 27 pm" src="https://cloud.githubusercontent.com/assets/5307471/10442513/8ef77d86-7118-11e5-8139-90ca6e0520ce.png">

Even with the fix from #1, the class inheritance overrides are not successfully applied:
<img width="750" alt="screen shot 2015-10-13 at 1 01 18 pm" src="https://cloud.githubusercontent.com/assets/5307471/10463481/8790aa08-71aa-11e5-8cfb-659ea38ce7e9.png">

**Workaround for the second part**
@nippur72's suggestion to alter the order of registration shows the correct override behavior:

``` typescript
// BOTTOM of base-element.ts

// WORKAROUND: Order registration from children in hierarchy to parent
NewElement.register();
BaseElement.register();
```

<img width="750" alt="screen shot 2015-10-13 at 1 02 58 pm" src="https://cloud.githubusercontent.com/assets/5307471/10463534/c541d8ae-71aa-11e5-88f4-952913c9506e.png">

This correctly allows the registration of a hierarchy of derived classes, and displays the expected behavior.

The workaround can be extended as long as the registration is done in child > parent hierarchy order, including multiple children of the same class.

``` typescript
// BOTTOM of base-element.ts

@component('third-element')
export class ThirdElement extends BaseElement {
}

// ThirdElement.register(); // Could place it here
NewElement.register();
ThirdElement.register();  // Or here: New/Third* are the same class level in hierarchy, so order does not trigger the error
BaseElement.register();
```

<img width="750" alt="screen shot 2015-10-13 at 1 14 15 pm" src="https://cloud.githubusercontent.com/assets/5307471/10463838/596211d8-71ac-11e5-954d-521c47dd3689.png">

So a temporary workaround until this issue is fixed is to keep your registration order from child to parent.

**Comment by BigBen1307** [comment]
> Polymer currently only supports extending native HTML elements (for example, input, or button, as opposed to extending other custom elements, which will be supported in a future release).

https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#type-extension

**Comment by kito99** [comment]
+1 This is annoying; perhaps register() shouldn't be so picky?

**Comment by kito99** [comment]
I'd like to avoid breaking backwards compatibility, and since most folks are looking to Polymer 2.0 at this point (see #110), I propose skipping this for now. If someone really wants this, we can re-open it.
