### ISSUE TITLE
PolymeTS does not play nice with vulcanize

### ISSUE THREAD

**Issue by DanielJoyce** [nippur72/PolymerTS#64]
Everything works until I try vulcanize ( needed for Chrome Apps ), then polymer-ts.js complains that Polymer is undefined, no matter where I stick the imports.

**Comment by DanielJoyce** [comment]
My application works as long as I don't vulcanize it, otherwise all custom components created by polymer-ts fail to load due to the above error.

**Comment by nippur72** [comment]
Have you checked the correct loading/importing sequence (explained [here](https://github.com/nippur72/PolymerTS#how-to-correctly-reference-in-markup)) ? 

I guess for some reason Polymer is loaded after the elements.

**Comment by DanielJoyce** [comment]
Yes I have. It works until I use Vulcanize.

**Comment by nippur72** [comment]
I just vulcanized the sample app of this project, and it works. 

Is your code in a public repo that I can clone and look into? Tell me how can I help.

**Comment by DanielJoyce** [comment]
Where did you put the polymerts imports? Polymer 1.0 reccomends polymer be imported by each custom element. I try adding polymer ts here as well, and I get the error after vulcanization.

https://github.com/DanielJoyce/microtome

**Comment by DanielJoyce** [comment]
gulp serve:dist

I have a dummy element for testing polymer-ts, my-derpderp. Instead of it rendering it shows up blank with a error in the console.

**Comment by DanielJoyce** [comment]
Nevermind. Project layout issue I think right now.

**Comment by DanielJoyce** [comment]
Nope, still happening.

**Comment by DanielJoyce** [comment]
Closing this out. Was an issue with my gulp build file and a weird interction between vulcanize and crisper for building as a chrome app.

**Comment by DanielJoyce** [comment]
// Vulcanize granular configuration
gulp.task('vulcanize', function() {
  var DEST_DIR = dist('elements');
  return gulp.src(dist('elements/elements.vulcanized.html'))
    .pipe($.vulcanize({
      stripComments: true,
      inlineCss: true,
      inlineScripts: true
    }))
    // DANGER DANGER DANGER
    // FOR Polymer-ts to work with polymer
    // Inside a chrome app, we MUST
    // have vulcanize INLINE scripts
    // Then use crisper to yank them all out again
    // Otherwise it will NOT work!!!
    .pipe(crisper())
    .pipe(gulp.dest(DEST_DIR))
    .pipe($.size({title: 'vulcanize'}));
});

This is what lets Polymer-TS work with Polymer inside a chrome app
