### ISSUE TITLE
Using polymer behaviors

### ISSUE THREAD

**Issue by EddieLa** [nippur72/PolymerTS#68]
Is using polymer behaviors, such as those from the neon-animation suite, supported in some manner? If not do you have any tips, tricks or advice about how to implement it?

Thanks.

**Comment by nippur72** [comment]
I've not checked it, but I think you can load the neon-animation suite and them write:
```TypeScript
@behaviour(Polymer.NeonAnimationBehavior)
class YourClassHere extends polymer.Base
```
(note that `Polymer` is the Polymer library, and `polymer` is PolymerTS).

Please let me know if that does not work.

**Comment by EddieLa** [comment]
I  went with:
```
@behaviour(Polymer["NeonAnimatableBehavior"])
class MyClass extends polymer.Base {
    @property()
    animationConfig: {
        ...
    }
}
```
It work's perfectly.
