### ISSUE TITLE
Is @property() required?

### ISSUE THREAD

**Issue by Draccoz** [nippur72/PolymerTS#71]
I've added a class attribute to my component class and did not decorate it with `@property` keyword. This is still accessible from node.attrName and can be used inside of template via binding. Is this some edge case, or is it supposed to behave like that? Code looks much nicer without it, but I don't want to use it if it breaks in some cases.

Thanks,
Dan

**Comment by nippur72** [comment]
It seems to me it's an edge case, are you sure binding is working? Anyway it's something related to Polymer and not PolymerTS, this because the `@property` decorator is just a shortcut for the `properties` object used when calling `Polymer({})`.

**Comment by Draccoz** [comment]
OK, I investigated polymer a bit, you were right :). This is Polymer itself.

Properties without `@property` end up as a top level attributes (siblings of `properties` object) and end up in Polymer constructor. Looks like (at least in this case) exactly every property of constructor object (or a class in case of TS) end up as a property, bound to the model.

I should have checked that before, thank you for a fast response and forgive my laziness :(.
