### ISSUE TITLE
set() supports arrays

### ISSUE THREAD

**Issue by nalbion** [nippur72/PolymerTS#72]
In the polymer-ts.d.ts you should have:

```
 set(path: string|[string, number], value: any, root?: Object): any;
```

**Comment by nippur72** [comment]
did you mean
```ts
set(path: string|[string|number], value: any, root?: Object): any;
```
(with `|` between `string` and `number`)

Or perhaps like in the docs:
```ts
set(path: string|Array<string|number>, value: any, root?: Object): any;
```

**Comment by nalbion** [comment]
Actually, according to the docs, the first element of the array is a string and the second should be "any". Typescript supports this Tuple syntax, so would be better to use comma rather than |


Specifically, Polymer provides two methods that allow such changes to be notified to the system: notifyPath(path, value) andset(path, value), where path is a stringidentifying the path (relative to the host element).

**Comment by nalbion** [comment]
Another one: `create(tag: string, props?: Object): HTMLElement;`

**Comment by nippur72** [comment]
sorry, I must be missing something, the docs from [http://polymer.github.io/polymer/](http://polymer.github.io/polymer/) have this signature for set(path, value, root):
```
path (string|Array<(string|number)>)
```
> The path may be specified as a string (e.g. foo.bar.baz) or an array of path parts (e.g. ['foo.bar', 'baz']).

I don't see where are the tuples.

**Comment by nalbion** [comment]
Okay, looking at the source, if you pass an array as the path, it calls `path[i].toString().split('.')`, so even if you do pass a number, it's going to be converted to a string anyway (just to be tested with `parseInt(part, 10) == part`), so the following are equivalent:

    this.set('myArray.1.name', 'Rupert');
    this.set('myArray.#1.name', 'Rupert');
    this.set(['myArray','1','name'], 'Rupert');
    this.set(['myArray','#1','name'], 'Rupert');
    this.set(['myArray',1,'name'], 'Rupert');
    this.set(['1','name'], 'Rupert', this.myArray);
    this.set([1,'name'], 'Rupert', this.myArray);
    
Ah - it took me a while to spot the last two, so yes - any element of the array can be a string or number.

Something like this would also work:

    this.set(1, {name: 'Rupert'}, this.myArray);

But obviously this wouldn't:

    this.set(1, {name: 'Rupert'});

...I suppose the full solution would be:

   set(path: string|Array<string|number>, value: any, root?: Object): any;
   set(path: number, value: any, root?: Array<any>): any;
   // something similar for get() and notifyPath()?
   create(tag: string, props?: Object): HTMLElement;

**Comment by nippur72** [comment]
I would like to adhere to the API specification as much as possible, so for now I've modified only `create` and `set` (in v0.1.23):
```ts
      create(tag: string, props?: Object): HTMLElement;
      set(path: string|Array<string|number>, value: any, root?: Object): any;
```
