### ISSUE TITLE
asyncOpt missing from importHref

### ISSUE THREAD

**Issue by bahrus** [nippur72/PolymerTS#74]
The polymer [api document ](https://www.polymer-project.org/1.0/api/#Polymer.Base:method-importHref ) for importHref indicates there's a fourth parameter, optAsync, of type Boolean.  I think this may have been added recently, as it is not mentioned [here](https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html).

That parameter is missing from the [type definition file.](https://github.com/nippur72/PolymerTS/blob/master/polymer-ts.d.ts)

**Comment by nippur72** [comment]
thank you, now it's in [0.1.24](https://github.com/nippur72/PolymerTS/releases/tag/0.1.24)
