### ISSUE TITLE
Default values for properties aren't honored when readOnly=true

### ISSUE THREAD

**Issue by kito99** [nippur72/PolymerTS#78]
Given this:

```
  @property({type: Boolean, readOnly: true})
  bubbles:boolean = false;
```

`this.bubbles ==  undefined` unless I remove the `readOnly` attribute (in which case it equals `false`, as expected).

**Comment by nippur72** [comment]
I've checked it and it seems to me a Polymer problem. I guess that when `readonly=true` polymer sets the property to its `value` (which is `undefined`). 

The only thing you can do is change it to:
```
 @property({type: Boolean, readOnly: true, value: false})
  bubbles:boolean;
```

**Comment by kito99** [comment]
Hmmm.. I'm guessing there's no way to throw an exception from the decorator in this case?
Also, the docs should say this won't work...
