### ISSUE TITLE
"Class constructor cannot be invoked without 'new'" error with es6 target

### ISSUE THREAD

**Issue by julesbou** [nippur72/PolymerTS#79]
Hi there,

I'm getting following error:

```
TypeError: Class constructor FooBarElement cannot be invoked without 'new' 
in polymer-ts:208
```

I'm using the `"target": "es6"` option in my `tsconfig.json` file, and my element looks like:

``` js
@component('foo-bar')
class FooBarElement extends polymer.Base {
...
}

FooBarElement.register();
```

I took a look at your issues and some of your code, including this PR https://github.com/nippur72/PolymerTS/pull/27/files which seems to add support for es6, but didn't found yet a solution to solve the error. 

Thanks for your work.

**Comment by nippur72** [comment]
I have to check it, but I think it won't work in pure ES6 targets due to the "hacks" it does.

Do you really need `ES6` or it's just a step in your build chain?

**Comment by julesbou** [comment]
> Do you really need ES6 or it's just a step in your build chain?

I would say no, but it's a nice to have in any modern project.

I'm using more and more `ES6` array functions like `find()`, which I found very handy for data manipulation. Of course as a workaround I could switch back to `ES5` and write it with a `for` loop.

**Comment by nippur72** [comment]
or you can target `es5` + `corejs` polyfill and continue writing ES6 as before. 

Unfortunately array prototype methods aren't transpiled by typescript, see the discussion at https://github.com/Microsoft/TypeScript/issues/3956

**Comment by Ptival** [comment]
Do you plan to eventually support ES6? It would be great.

**Comment by nippur72** [comment]
unfortunately it's not possible with the current implementation of Polymer, but perhaps in the future there will be a version of Polymer that is more ES6-friendly.

**Comment by kito99** [comment]
@nippur72 now is the time, with Polymer 2 :-).

**Comment by kito99** [comment]
Closing this, since most folks are looking to Polymer 2.0 which fully embraces ES6 at this point (see #110), I propose skipping this for now. If someone really wants this, we can re-open it.
