### ISSUE TITLE
What is the right way to wait for an element's constructor to be done

### ISSUE THREAD

**Issue by Ptival** [nippur72/PolymerTS#80]
Say I have:

````
export class MyElement extends polymer.Base {
  field: number;

  constructor(n: number) {
    super();
    this.field = n;
  }
}
````

And I do:

````
const myElement = MyElement.create(arg);
Polymer.dom(someContainer).appendChild(myElement);

// I would like to access myElement.field after it is set by the constructor
````

AFAIU, the constructor (which is actually the `factoryImpl`) might not have been called yet at the bottom. What should I do in order to make sure that when I access myElement.field, the constructor has run? Is there an event/callback I can latch on, or do I need to implement some logic myself?

Thanks!

**Comment by nippur72** [comment]
You can use lifecycle events to know when the element is ready, and then fire a custom event. Outside of the element you have to listen to that custom event.

Something like this (I've not tested it but it should work):
```ts
export class MyElement extends polymer.Base {
  field: number;
  constructor(n: number) {
    super();
    this.field = n;
  }
  attached() { // or created, ready etc... see lifecycle events
    this.fire("myel-attached");
  }
}

const myElement = MyElement.create(arg);
myElement.addEventListener('myel-attached', function (e) {
    // here you can access myElement.field        
}) 
Polymer.dom(someContainer).appendChild(myElement);
```

**Comment by Ptival** [comment]
Thanks, that's what I was heading towards, just wanted to make sure I wasn't missing on some existing hook.
