### ISSUE TITLE
Behaviors not working in decorator-less definitions of a component

### ISSUE THREAD

**Issue by faGH** [nippur72/PolymerTS#83]
behaviors: any[] = [
            FrostAura.Dynamics.Client.Behaviours.Core.FaCoreBehaviour
        ];

doesn't seem to work. Nor does (Becaue the polymer.Base extending makes it un-newable):
behaviors: any[] = [
            new FrostAura.Dynamics.Client.Behaviours.Core.FaCoreBehaviour()
        ];

Am I doing this incorrectly or is it not yet supported?

**Comment by kito99** [comment]
You need to use the approach to using behaviors that's discussed in the README: https://github.com/Polymer/polymer-decorators
