### ISSUE TITLE
Definitely typed components do not appear in automated documentation list (iron-component)

### ISSUE THREAD

**Issue by faGH** [nippur72/PolymerTS#85]
Definitely typed components do not appear in automated documentation list (iron-component)

**Comment by danielvanmil** [comment]
any progress on this issue?

**Comment by faGH** [comment]
Not to my knowledge. I am in the process of making my own automated document similar to that of Polymer.

Can let you know when this is done?

Sent from my iPhone

On 17 Nov 2016, at 11:49, danielvanmil <notifications@github.com<mailto:notifications@github.com>> wrote:


any progress on this issue?

**Comment by kito99** [comment]
@faGH, I think this is really an iron-component-page bug. see https://github.com/PolymerElements/iron-component-page/issues/108
