### ISSUE TITLE
Versioned polymer elements?

### ISSUE THREAD

**Issue by oleersoy** [nippur72/PolymerTS#87]
Hi,

First wanted to say thanks for creating this library.  It's really impressive.  

I'm trying to figure out the best way to remove element collisions when creating transitive components.  For example suppose one component in the app (`component-a`) is using the `my-timer` element version 1.  And another component also wants to use the `my-timer` element but it needs to use version2.

So this implies that the app needs two versions of the `my-timer` element, but that will cause conflicts when polymer tries to register the `my-timer` element.  

So I was wondering whether you think there exists a simple way to include / inject a version number into the polymer element as it's compiled from typescript.  So for example include a build option called `versionize` and if it's true then elements for transitive component dependencies would be generated as:

`my-timer@1.2.3`

And so polymer registration of these elements would still succeed because the `component-a` would be defined like this:

```
<component-a><my-timer@1.2.3 value="42"><my-timer@1.2.3></component-a>
```

Instead of 

```
<component-a><my-timer value="42"><my-timer></component-a>
```

Or maybe there is a better way?  Thank you again for creating PolymerTS and if you feel like this is outside the scope of the project, please feel free to close the issue.

**Comment by nippur72** [comment]
Hmm... having two versions of the same component in the same app is something that's going to give you lots of headaches! Honestly I don't think we should encourage that :-)

Also, what you describe is a problem common to all WebComponents, not just Polymer or PolymerTS, so I would look around seeing if that has been already solved (spoiler: a quick google search reveals it ain't).

Anyway, if you are forced to do that (registering two components that share the same name) you could try by hacking `document.registerElement`:
```HTML
<script>
(function() {
   var oldRegisterElement = document.registerElement;
   var count=0;
   document.registerElement = function(name,opts) {
      if(name=="my-timer") name += "-" + String(count++);
      oldRegisterElement(name, opts);
   }
})();
</script>
<link rel="import" href="v1.0/timer.html" />
<link rel="import" href="v2.0/timer.html" />
```
that should register the first `my-timer` as `my-timer-1`  and the second as `my-timer-2`. 

I have not tested it, but in theory it should work.

**Comment by oleersoy** [comment]
Hi there - and thank you very much for your input!  We've been having a long discussion about this here https://github.com/Polymer/polymer/issues/326 and I started another issue to track progress here:
https://github.com/Polymer/polymer/issues/3875

In general I was thinking that renaming of elements would be applied to transitive dependencies that have a version conflict with a top level element.  That way we can defer dealing with conflicts until after the prototyping stage when assembling various components from "The wild".    

So in the above example (yours) we may use v2 of the timer as a top level element, but then we add another component, `stop-watch` that pulls in timer version 1.  Ideally we could just keep prototyping the app without having to stop and fix the version issue, like we do with node apps.
