### ISSUE TITLE
Using Typescript Module 

### ISSUE THREAD

**Issue by bsorrentino** [nippur72/PolymerTS#9]
Hi

What do you think to use module to better organize  the polymer typescript?

Below my suggestion :

```typescript

module polymer {

export class Base { ... }

export interface Element { ... }

export interface propDefinition { ... }

}  // end module

interface Polymer { ... }

declare var Polymer: Polymer;

function component(tagname: string) { ... }

function extend(tagname: string) { ... }

function hostAttributes(attributes: Object) { ... }

function property(ob: polymer.propDefinition) { ... }

function computed(ob?: polymer.propDefinition) { ... }

function listener(eventName: string) { ... }

function behavior(behaviorObject: any): any { ... }

function observe(propertiesList: string) { ... }

function createElement(element: Function): void { ... }

function createClass(element: Function): void { ... }

```

**Comment by nippur72** [comment]
Thanks for the suggestion, it's really appreciated as I'm rather new to TypeScript and its module architecture (I still have to get used).

**Comment by nippur72** [comment]
Ok, rewrote everything as a module as by your suggestion, now:
- `base` is `polymer.Base`
- `PolymerElement` is `polymer.Element`

If you have other tips, they are welcome :smile:

**Comment by bsorrentino** [comment]
Hi 

Great work

Now looks much better ... I'm gonna to write an article on my blog that mentions this great project

**Comment by bsorrentino** [comment]
as promised the article

[POLYMER + TYPESCRIPT the marvelous couple](http://soulsoftware-bsc.blogspot.it/2015/07/polymer-typescript-marvelous-couple.html)
