### ISSUE TITLE
Polymer 2 support

### ISSUE THREAD

**Issue by kito99** [nippur72/PolymerTS#90]
Google just announced Polymer 2: https://github.com/polymer/polymer/tree/2.0-preview.. Any thoughts on how much work it's going to be to upgrade PolymerTS?

**Comment by nippur72** [comment]
With the new ES6 syntax, PolymerTS can do much less work than before, I think it can even shrink down to "just decorators". 

Also those using PolymerTS as of now are advantaged because they are already writing components as classes.

**Comment by kwaclaw** [comment]
Seems there is also this branch: https://github.com/polymer/polymer/tree/2.0-typescript

**Comment by kito99** [comment]
Interesting, @kwaclaw... looks like they will make Polymer a first-class TypeScript citizen ;-).

**Comment by tpluscode** [comment]
Well, when Polymer becomes a first-class ES6 citizen, it will be transitively a full TS citizen. This is very good news.

**Comment by tpluscode** [comment]
Interestingly, the TS branch actually already includes some [decorators](https://github.com/Polymer/polymer/blob/2.0-typescript/src/typescript/decorators.d.ts).

`function customElement(tagname: string)`, `function property<T>(options?: PropertyOptions)` and `function observe(targets: string | string[])` would likely replace those of PolymerTS if TypeScript does actually become an officially supported flavour of Polymer.

If so, I'd vote for pull-requesting (is that a verb) any decorators from here to Polymer and leave only anything that the Polymer team doesn't feel like supporting out-of-the-box.

**Comment by Whyser** [comment]
Im not very well versed in the internals of TS and Polymer, but will it be equivalent "easy" to make this repo support TypeScript 2? 

Thanks for your great work!

**Comment by kito99** [comment]
@Whyser, I don't think anything is required to make this repo support TS 2. I'm using PolymerTS with TS 2 in a few different repos without any issues.

**Comment by kito99** [comment]
Yes, @tpluscode, I know -- I started the thread :-). I was just answering his question since he brought it up.

**Comment by kito99** [comment]
@nippur72, since the Polymer team hasn't made substantial progress on official TypeScript support, are there any plans for upgrading PolymerTS for Polymer 2?

**Comment by kito99** [comment]
The Polymer team finally has released [official decorators](https://github.com/Polymer/polymer-decorators), so I'll be focusing on making it easy to transition from Polymer 1.0/PolymerTS to the Polymer 2.0/PolymerDecorators rather than adding support for Polymer 2. I have created #110 to track this.
