### ISSUE TITLE
Error build project using `Polymer build`.    

### ISSUE THREAD

**Issue by felipesousa** [nippur72/PolymerTS#91]
I am using `Polymer CLI` to build my project, including POLYMER-TS I have that problem when run the command `polymer build`

```
$ polymer build                                                                                                               
info:    Preparing build...
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Promise rejection: Error: file path is not in root: /bower_components/polymer-ts/polymer-ts.js (/Users/<my-user>/<path/the/project>)
error:   Error: file path is not in root: /bower_components/polymer-ts/polymer-ts.js (/Users/<my-user>/<path/the/project>)
```

**Comment by cbfranca** [comment]
+1

**Comment by kito99** [comment]
You may need a custom build script to include TypeScript (I use gulp). One option may be to compile first via tsc and then run polymer-cli, but you are probably better off using the process that the polymer-init-custom build uses (https://github.com/PolymerElements/generator-polymer-init-custom-build) with gulp and the gulp-typescript plugin.

**Comment by kito99** [comment]
In general, with TypeScript you either need to use a custom build script or https://github.com/PolymerElements/generator-polymer-init-custom-build.
