### ISSUE TITLE
Support for polymer-redux

### ISSUE THREAD

**Issue by pme123** [nippur72/PolymerTS#92]
I created an example that uses [polymer-redux](https://github.com/tur-nr/polymer-redux) with Typescript: 
https://github.com/pme123/polymer-redux-typescript-example

It works - but I have 2 open points. One of them I think I have to address here:

- polymer-redux extends the Polymer.property with the argument 'statePath' which throws a transpile exception as this argument is not in the defined type.

Is there a way that this will be possible (no transpile problem)?

**Comment by nippur72** [comment]
there are two possible workarounds:
- the most obvious is to cast to any: 
```ts
@property({type: Object, statePath: 'customer'} as any)
```
- the other is to rewrite the `@property` decorator, e.g.:
```ts
// notice the uppercase "P"
function Property(ob?: any) {
   return property(ob as any);   
}
```

**Comment by pme123** [comment]
thanks, the first one works well for me (sorry I haven't seen that one)
